{% set name = "visit_struct" %}
{% set version = "1.2.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/cbeck88/visit_struct/archive/refs/tags/{{ version }}.tar.gz
  sha256: aa0f4cc674ee584e0498604971c8bbdc0eeb7d6d6386c95695211b0418ff2bef

build:
  number: 0

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - ninja

test:
  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - ninja
    - cmake
  files:
    - test
  commands:
    - test -f ${PREFIX}/include/visit_struct/visit_struct.hpp  # [not win]
    - test -f ${PREFIX}/share/visit_struct/visit_struct-config.cmake  # [not win]
    - if not exist %LIBRARY_INC%\\visit_struct\\visit_struct.hpp exit 1  # [win]
    - if not exist %PREFIX%\\Library\\share\\visit_struct\\visit_struct-config.cmake exit 1  # [win]

about:
  home: https://github.com/cbeck88/visit_struct
  license: BSL-1.0
  license_file: LICENSE
  summary: A miniature library for struct-field reflection in C++.

extra:
  recipe-maintainers:
    - traversaro
